#!/usr/bin/bash
cd /data/data/com.termux/files/home/.termux/tasker/js/

while getopts ":m:u:wlh" opt; do
  case $opt in
    u)
      username="$OPTARG"
      ;;
    m)
      if [[ -n $username ]]; then
        node shell-telegram.js -m "$OPTARG" -u $username
      else
        node shell-telegram.js -m "$OPTARG"
      fi
      ;;
    w)
      node shell-telegram.js -w
      ;;
    l)
      cat /storage/emulated/0/Documents/automate/outing.txt | node shell-telegram.js -l
      ;;
    h)
      node shell-telegram.js -h
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done


